### ISSUE TITLE
User\password for example repository

### ISSUE THREAD

**Issue by dsryzhov** [Open-MBEE/exec-mms#112]
Hi, 

Trying to connect to test mms repository (server was run using docker-compose as described on the page https://github.com/Open-MBEE/mms)

Please specify  what's username\password should be used for connection to server from Capella?

using server url
http://localhost:8080/alfresco/service

Regards,
Dmitry

**Comment by dlamoris** [comment]
Can you give more details about what you're testing?
A better repo for a quick start right now would be https://github.com/Open-MBEE/mmsri - it's the standalone example from this repo with more production oriented config options. If you're using the compose file, it takes the admin username and pass from here: https://github.com/Open-MBEE/mmsri/blob/develop/src/main/resources/application-test.properties (test, test)
the url is just http://localhost:8080, there's no more alfresco/service.

**Comment by dsryzhov** [comment]
Hi,

Thanks for your response. I will try to run MMS repo locally based on your links.

I am trying to use Polarsys Capella integration with MMS 
https://github.com/labs4capella/mms-capella

The main my goal is to provide documents'view for Capella models with the possibility
to read, comment and edit them via VE. 

By this time I was able to use public MMS repo to export Capella models.
https://mms.openmbee.org/

Currently Capella-MMS integration does not help to cross reference 
Capelle elements in VE, see my issue 
https://github.com/labs4capella/mms-capella/issues/11
But I think this possibility will be added (by developers or by me)

Now we use M2Doc https://www.m2doc.org/
to publish Word and html documents from Capella models.
Now we think about possibility to publish documents to MMS and vied\comment\edit them in VE.

Regards,
Dmitry

**Comment by dsryzhov** [comment]
Can't connect to started MMS server from mmsri
have added issue
https://github.com/Open-MBEE/mmsri/issues/3

**Comment by dlamoris** [comment]
Ah, what you want is actually the previous version of mms here https://github.com/Open-MBEE/mms-alfresco/blob/develop/mms-ent/docs/quick-start.md
This repo is the next major release that has some breaking changes, and is currently in beta.
