### ISSUE TITLE
Update Documentation to describe how to externalize config files

### ISSUE THREAD

**Issue by Enquier** [Open-MBEE/exec-mms#115]
The current documentation only identifies the way to package a config file inside the jar. Documentation should be added (a link?) to spring.io or a short TLDR which describes how K8S and Swarm loads can mount the properties without rebuilding the jar/container

**Comment by dlamoris** [comment]
link to spring doc added to readme at the mmsri repo, more specific examples may come later depending on what specific scenarios people want examples for (prs welcome)
