### ISSUE TITLE
Cannot login to locally installed mms from MDK plugin

### ISSUE THREAD

**Issue by iman-badr** [Open-MBEE/exec-mms#130]
Hi all,
I could run bootRun and access mms at http://localhost:8080. However, when I attempt to connect to it from the MDK plugin it fails
![grafik](https://user-images.githubusercontent.com/72130505/102060225-35449880-3df2-11eb-8e7f-5824ac3aa7b5.png)
![grafik](https://user-images.githubusercontent.com/72130505/102059735-95870a80-3df1-11eb-9d5f-d6894f270a1e.png)
I am missing something? Can anyone please help me?
Best regards, 
Iman

**Comment by BA-MBSE** [comment]
The MMS 4 compatible MDK is still under development.  There’s a PR here https://github.com/Open-MBEE/mdk/pull/193 that’s under review.

Ward

**Comment by iman-badr** [comment]
@BA-MBSE thank you for your reply. I am waiting for the changes to be merged and will try again. I hope the link I am using will work after these changes
Regards,
Iman

**Comment by ivan-gomes** [comment]
Hi @iman-badr, a snapshot build of mdk-5.0.0-rc1, working towards compatibility with mms4, is linked in https://github.com/Open-MBEE/mdk/pull/193#issuecomment-745475387. We can continue the MDK related discussion there.
