### ISSUE TITLE
Unable to perform partial-text Search on documentation, and name

### ISSUE THREAD

**Issue by Enquier** [Open-MBEE/exec-mms#188]
I'm getting a 500 error when I attempt a simple partial text query on certain fields:
documentation
name

When I attempt to search for a partial or even full text match on those fields I get an error:

eg.

<server_url>/projects/<project-id>/refs/master/search)
--header 'Content-Type: application/json' \
--data-raw '{
    "params": {
        "documentation": "The purpose"
    }
}'

If this text is not present I would expect an empty return, however I know this text is present in my model.

**Comment by Enquier** [comment]
This seems to be the code that is at issue:

[https://github.com/Open-MBEE/mms/blob/e46867e6e5a56ef813e7bb2ffebcbc1c0aed599e/ela[…]ava/org/openmbee/mms/elastic/services/ElasticSearchService.java](https://github.com/Open-MBEE/mms/blob/e46867e6e5a56ef813e7bb2ffebcbc1c0aed599e/elastic/src/main/java/org/openmbee/mms/elastic/services/ElasticSearchService.java#L196)
[ElasticSearchService.java](https://github.com/Open-MBEE/mms/blob/e46867e6e5a56ef813e7bb2ffebcbc1c0aed599e/elastic/src/main/java/org/openmbee/mms/elastic/services/ElasticSearchService.java)
        SearchRequest searchRequest = new SearchRequest(Index.NODE.get());

**Comment by dlamoris** [comment]
should be fixed
