### ISSUE TITLE
differences in branches and nested branches don't show in clients accessing API in MMS4

### ISSUE THREAD

**Issue by HuiJun** [Open-MBEE/exec-mms#214]
when diffing branches and nested branches using LemonTree Web for example, the differences don't show up. Also not in VE.
example changes: added views, changed text in the presentation elements

https://openmbee.atlassian.net/jira/software/c/projects/MMS/issues/MMS-142

**Comment by dlamoris** [comment]
this may just be because of the ve bug and the config error when that test is made, mms itself should be fine

**Comment by dlamoris** [comment]
cannot reproduce
