### ISSUE TITLE
MMS server accepts commits with invalid json data

### ISSUE THREAD

**Issue by aschoelzhorn** [Open-MBEE/exec-mms#233]
Problem:
MMS server accepts a commit from the OpenAPI even if the data in the json is invalid. We used strings as values for a boolen type. The MMS server accepted it, but syncing from MMS to TCW doesn't work anymore. 

![image](https://user-images.githubusercontent.com/1025417/222473309-e4ae8199-7d4f-409b-b286-14a40fd780a3.png)

Expectation:
The MMS server rejects commits with invalid json data.

**Comment by dlamoris** [comment]
mms is schema agnostic, it'll accept any valid json and doesn't validate against any particular json schema (ex. you can add any key-value pair to an object and it'll be stored). It's up to the client to send 'valid' data
