### ISSUE TITLE
Cannot branch from point in time (specific commit)

### ISSUE THREAD

**Issue by HuiJun** [Open-MBEE/exec-mms#237]
Currently, MMS does not support branching from a specific commit, only head of ref.

https://github.com/Open-MBEE/mms/blob/b538d2416766965d848f3edc4b6290302b1aaf10/crud/src/main/java/org/openmbee/mms/crud/services/DefaultBranchService.java#L143-L147

**Comment by dlamoris** [comment]
possibly we can just get all elements at commit (there should already be a function for that) and use that data to update the new ref table, need to set deleted though
